example/example_app/urls.py
from django.conf.urls import url

from . import views

app_name = 'example_app'

urlpatterns = [
    url(r'^$', views.ItemListView.as_view(), name='index'),
    url(r'^item/(?P<pk>\d+)$', views.ItemDetailView.as_view(), name='view'),
    url(r'^item/(?P<pk>\d+)/edit$', views.ItemUpdateView.as_view(), name='update'),
    url(r'^item/create$', views.ItemCreateView.as_view(), name='create'),
]

example/example_project/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    url(r'^', include('example_app.urls')),
    url(r'^', include('django.contrib.auth.urls')),
    url(r'^admin/', admin.site.urls),
]

example/example_app/models.py
from django.db import models
from temporal_django import add_clock, Clocked

from django.contrib.auth.models import User


class ItemActivity(models.Model):
    description = models.TextField()
    author = models.ForeignKey(User, blank=True, null=True)

    @staticmethod
    def temporal_queryset_options(queryset):
        return queryset.select_related('activity__author')


@add_clock('title', 'number', 'effective_date', activity_model=ItemActivity)
class Item(Clocked):
    title = models.CharField(max_length=100)
    number = models.IntegerField()
    effective_date = models.DateField()

example/example_app/forms.py
from django import forms

from .models import Item


class ItemForm(forms.ModelForm):
    description = forms.CharField(
        widget=forms.Textarea(attrs={'placeholder': 'Why are you making this change?'}),
        label='Activity description')

    class Meta:
        model = Item
        fields = ['title', 'number', 'effective_date', 'description']
        widgets = {
            'effective_date': forms.DateInput(attrs={'type': 'date'}),
        }

example/example_app/views.py
from django.http import HttpResponseRedirect
from django.urls import reverse
from django.views.generic.detail import DetailView
from django.views.generic.edit import CreateView, UpdateView
from django.views.generic.list import ListView

from .models import Item, ItemActivity
from .forms import ItemForm


class ItemDetailView(DetailView):
    model = Item


class ItemUpdateView(UpdateView):
    model = Item
    form_class = ItemForm

    def form_valid(self, form):
        self.object = form.save(commit=False)
        self.object.save(activity=ItemActivity(
            description=form.cleaned_data['description'],
            author=self.request.user if self.request.user.is_authenticated() else None
        ))
        return HttpResponseRedirect(self.get_success_url())

    def get_success_url(self):
        return reverse('example_app:view', args=(self.object.id,))


class ItemCreateView(CreateView):
    model = Item
    form_class = ItemForm

    def form_valid(self, form):
        self.object = form.save(commit=False)
        self.object.save(activity=ItemActivity(
            description=form.cleaned_data['description'],
            author=self.request.user if self.request.user.is_authenticated() else None
        ))
        return HttpResponseRedirect(self.get_success_url())

    def get_success_url(self):
        return reverse('example_app:view', args=(self.object.id,))


class ItemListView(ListView):
    model = Item

    def get_context_data(self, **kwargs):
        context = super(ItemListView, self).get_context_data(**kwargs)
        return context

example/example_app/templates/example_app/base.html
<!doctype html>
<html lang="en">
  <head>
    <title>temporal-django example app</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta.2/css/bootstrap.min.css" integrity="sha384-PsH8R72JQ3SOdhVi3uxftmaW6Vc51MKb0q5P2rRUpPvrszuE4W1povHYgTpBfshb" crossorigin="anonymous">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" integrity="sha384-wvfXpqpZZVQGK6TAh5PVlGOfQNHSoD2xbE+QkPxCAFlNEevoEH3Sl0sibVcOQVnN" crossorigin="anonymous">
    <style>
      body {
        padding-top: 5rem;
      }
    </style>
  </head>
  <body>
    <nav class="navbar navbar-expand-md navbar-dark bg-dark fixed-top">
      <a class="navbar-brand" href="/">Temporal Django example app</a>
      <div class="collapse navbar-collapse" id="navbarsExampleDefault">
        <ul class="navbar-nav mr-auto">
          <li class="nav-item">
            <a class="nav-link" href="/">Items</a>
          </li>
        </ul>
        <form class="form-inline my-2 my-lg-0">
          <a href="{% url 'example_app:create' %}" class="btn btn-outline-primary my-2 my-sm-0">Create an item</a>
          &nbsp;
          {% if user.is_authenticated %}
            <a href="{% url 'logout' %}?next=/" class="btn btn-primary my-2 my-sm-0" title="Logged in as {{ user.username }}">Logout</a>
          {% else %}
            <a href="{% url 'login' %}" class="btn btn-primary my-2 my-sm-0">Login</a>
          {% endif %}
        </form>
      </div>
    </nav>

    <main role="main" class="container">
      {% block content %}{% endblock %}
    </main>
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.3/umd/popper.min.js" integrity="sha384-vFJXuSJphROIrBnz7yo7oB41mKfc8JzQZiCq4NCceLEaO4IHwicKwpJf9c9IpFgh" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta.2/js/bootstrap.min.js" integrity="sha384-alpBpkh1PFOepccYVYDB4do5UnbKysX5WZXm3XxPqe5iKTfUKjNkCk9SaVuEZflJ" crossorigin="anonymous"></script>
  </body>
</html>

example/example_app/templates/example_app/item_detail.html
{% extends 'example_app/base.html' %}

{% block content %}
<div class="row">
  <div class="col">
    <h1>{{ item.title }}</h1>
  </div>
  <div class="col">
    <a href="{% url 'example_app:update' item.id %}" class="pull-right btn btn-primary">
      Edit item <span class="fa fa-edit"></span>
    </a>
  </div>
</div>
<div class="row">
  <div class="col">
    <h2>Item properties</h2>
    <dl>
      <dt>Title</dt>
      <dd>{{ item.title }}</dd>

      <dt>Number</dt>
      <dd>{{ item.number }}</dd>

      <dt>Effective Date</dt>
      <dd>{{ item.effective_date }}</dd>
    </dl>
  </div>
  <div class="col">
    <h2>Item history</h2>
    {% for timeline_entry in item.temporal_timeline %}
      <div class="card">
        <div class="card-body">
          <p class="small text-muted pull-right">{{ timeline_entry.clock.timestamp }}</p>
          <p>
            {% if timeline_entry.clock.tick == 1 %}Created{% else %}Modified{% endif %} by
            {% if timeline_entry.clock.activity.author %}
              {{ timeline_entry.clock.activity.author }}
            {% else %}
              Anonymous user
            {% endif %}
          </p>
          <blockquote class="blockquote">{{ timeline_entry.clock.activity.description|linebreaks }}</blockquote>
          <ul>
            {% for field in timeline_entry.changed_fields.values %}
              <li>Set <strong>{{ field.label }}</strong> to <code>{{ field.value }}</code></li>
            {% endfor %}
          </ul>
        </div>
      </div>
    {% endfor %}
  </div>
</div>
{% endblock %}

example/example_app/templates/example_app/item_form.html
{% extends 'example_app/base.html' %}
{% load crispy_forms_tags %}

{% block content %}
<div class="row">
  <div class="col">
    <form action="" method="post">{% csrf_token %}
      <h2>{% if object %}Edit{% else %}Create{% endif %} item</h2>
      {{ form|crispy }}
      <input type="submit" class="btn btn-primary" value="{% if object %}Save{% else %}Create{% endif %}" />
    </form>
  </div>
</div>
{% endblock %}

example/example_app/templates/example_app/item_list.html
{% extends 'example_app/base.html' %}

{% block content %}
  <div class="row">
    <div class="col">
      {% if object_list %}
        <h2>Items</h2>
        <table class="table table-responsive">
          <thead>
            <th>Title</th>
            <th>Effective Date</th>
            <th>Date Created</th>
            <th>Date Modified</th>
            <th>Last Edited By</th>
            <th>Revisions</th>
            <th>Actions</th>
          </thead>
          <tbody>
          {% for item in object_list %}
            <tr>
              <td><a href="{% url 'example_app:view' item.id %}">{{ item.number }}. {{ item.title }}</a></td>
              <td>{{ item.effective_date }}</td>
              <td>{{ item.date_created }}</td>
              <td>{{ item.date_modified }}</td>
              <td>
                {% if item.latest_tick.activity.author %}
                {{ item.latest_tick.activity.author }}
                {% else %}
                Anonymous user
                {% endif %}
              </td>
              <td>{{ item.clock.count }}</td>
              <td>
                <a href="{% url 'example_app:update' item.id %}">
                  Edit <span class="fa fa-edit"></span>
                </a>
              </td>
            </tr>
          {% endfor %}
          </tbody>
        </table>
      {% else %}
        <p>There are no items yet. Create an item to start.</p>
      {% endif %}

      <a href="{% url 'example_app:create' %}" class="btn btn-outline-primary">Create an item</a>
    </div>
  </div>
{% endblock %}